### ISSUE TITLE
Failing to POST ClusterRole and ClusterRoleBinding

### ISSUE THREAD

**Issue by alewitt** [godaddy/kubernetes-client#157]
- Im trying to apply ymls that looks similar to this (the service account already exists):
```
    apiVersion: rbac.authorization.k8s.io/v1alpha1
    kind: ClusterRole
    metadata:
      namespace: chaos
      name: chaos
      annotations:
        version: dev
    rules:
      # add and delete namespaces, pods and deployments
      - apiGroups: [""]
        resources: ["namespaces", "pods"]
        verbs: ["get", "watch", "list", "create", "delete", "deletecollection"]
        nonResourceURLs: []
      - apiGroups: ["extensions"]
        resources: ["deployments", "replicasets"]
        verbs: ["get", "watch", "list", "create", "delete", "deletecollection"]
        nonResourceURLs: []
      # manage configmaps; primarily for self config and save state
      - apiGroups: [""]
        resources: ["configmaps"]
        verbs: ["get", "create", "update", "delete"]
      # get nodes and change state
      - apiGroups: [""]
        resources: ["nodes"]
        verbs: ["get", "watch", "list", "update"]
        nonResourceURLs: []
```

```
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1alpha1
    metadata:
      namespace: chaos
      name: chaos
      annotations:
        version: dev
    subjects:
      - kind: ServiceAccount
        name: chaos
        namespace: chaos
    roleRef:
      kind: ClusterRole
      name: chaos
      apiGroup: rbac.authorization.k8s.io
```

- the code that applies the ymls:
```
const Api = require('kubernetes-client');
const api = Api.Api(Api.config.getInCluster());
function kubePost(yml) {
  return new Promise(function (resolve, reject) {
      api.group(yml).ns(yml.metadata.namespace).kind(yml).post({
        body: yml
      }, function postResult(err, result) {
        if (err) {
          reject(err);
        } else {
          resolve(result);
        }
      });
  });
}
```

- Receiving the following error:
```
Error: the server could not find the requested resource
        at /<mypath>/node_modules/kubernetes-client/lib/base.js:11:21
        at Request.request [as _callback] (/<mypath>/node_updater/node_modules/kubernetes-client/lib/api-group.js:127:7)
        at Request.self.callback (/<mypath>/node_modules/request/request.js:186:22)
        at emitTwo (events.js:125:13)
        at Request.emit (events.js:213:7)
        at Request.<anonymous> (/<mypath>/node_updater/node_modules/request/request.js:1163:10)
        at emitOne (events.js:115:13)
        at Request.emit (events.js:210:7)
        at IncomingMessage.<anonymous> (/<mypath>/node_updater/node_modules/request/request.js:1085:12)
        at Object.onceWrapper (events.js:314:30)
```

- i dont understand why it would fail with this error, it shouldnt need to find a resource when its posting. Please help! thanks
