### ISSUE TITLE
kube config user exec without optional properties causes TypeError

### ISSUE THREAD

**Issue by grounded042** [godaddy/kubernetes-client#350]
If I create a config using `fromKubeconfig` and the user auth is exec with the following authInfo in kube config:

```yaml
- name: my-k8s-cluster-context
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - first-arg
      command: some-executable-path
```

I get the error `TypeError: Cannot read property 'forEach' of undefined` because the optional `env` property is not set.

Also, if I instead have the following authInfo in kube config:

```yaml
- name: my-k8s-cluster-context
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: some-executable-path
      env:
      - name: "FOO"
        value: "bar"
```

I get the error `TypeError: Cannot read property 'join' of undefined` because the optional `args` property is not set.

The `args` and `env` properties are optional and should be handled that way in the code. I'll have a PR for this shortly and am creating this issue to document what the PR will be fixing.
