### ISSUE TITLE
How to create a job from cronjob programmatically?

### ISSUE THREAD

**Issue by sudheer-sweetiq** [godaddy/kubernetes-client#443]
I would like to run a cronjob programmatically using the following command, Can anyone help on this?
`kubectl create job --from=cronjob/test-job test1`

**Comment by silasbw** [comment]
I haven't used jobs much, beyond playing around with them, and I don't know specifically how `kubectl` implements that command.  One approach for doing this with kubernetes-client is to:

1. get the CronJob object [apis.batch.v1beta1.namespaces(namespace).cronjobs(name).get](https://github.com/godaddy/kubernetes-client/blob/master/docs/1.13/CronJob.md#apisbatchv1beta1namespacesnamespacecronjobsnameget)
2. extract the `jobSpec` from the result of 1. (see [Automated Tasks with Cron Jobs](https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/) for some examples of the CronJob object)
3. use the `jobSpec` from 2. to construct a Job manifest and create a new Job [apis.batch.v1.namespaces(namespace).jobs.post](https://github.com/godaddy/kubernetes-client/blob/master/docs/1.13/Job.md#apisbatchv1namespacesnamespacejobspost)

Please share what you come up with and we can include it with the other [examples/](https://github.com/godaddy/kubernetes-client/tree/master/examples)

**Comment by pavloomelchenko** [comment]
@silasbw Thanks!, it worked for me in java(client-java:8.0.0)

**Comment by nipunshahs** [comment]
@silasbw Thanks for your input I am in need of same implementation, I am new to apis and wondering how it will be implemented at code level. can you please share sample code? Thanks a lot

**Comment by Babak-abd** [comment]
code:
```
ApiClient client = Config.defaultClient();
Configuration.setDefaultApiClient(client);

File file = new File("cronJob.yaml");
V1CronJob yamlCronJob = (V1CronJob) Yaml.load(file);

BatchV1Api batchAPI = new BatchV1Api();
 V1CronJob createNamespacedCronJob = batchAPI.createNamespacedCronJob("default", yamlCronJob, "true", null, null, null);
```

cronJob.yaml
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```
