### ISSUE TITLE
How to use specific api from GKE?

### ISSUE THREAD

**Issue by nicolasgere** [godaddy/kubernetes-client#457]
Hi there, 
I working on an automating tools for GCP, and i'm wondering how to use to target a specific api with your library. I try some stuff without success. It's for GKE ingress using networking.gke.io/v1beta1
```
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: example-certificate
spec:
  domains:
    - example.com
```

Thank you
