### ISSUE TITLE
How do I get Custom Resource Definition properties?

### ISSUE THREAD

**Issue by sfxworks** [godaddy/kubernetes-client#458]
I created a namespaced scope CRD. 
```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: payloads.hook-to-k8s.sfxworks.net
spec:
  group: hook-to-k8s.sfxworks.net
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: payloads
    singular: payload
    kind: Payload
    shortNames:
    - pl
    - payl
```

I am able to run `kubectl-proxy` and see that my CRD is active via http://127.0.0.1:8001/apis/hook-to-k8s.sfxworks.net/v1

With the client configured to use a service account in the pod and the pod configured to use a service account that has the proper Role/Role bindings, I get an error when trying to access this resource.

Using
`const payloads = await client.apis["hook-to-k8s"].sfxworks.net.v1.namespaces.default.payloads.get()`
I get 
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sfxworks' of undefined
```
I have tried renaming this several ways, including
`  const payloads = await client.apis["hook-to-k8s.sfxworks.net"].v1.namespaces.default.payloads.get() `

and I still get undefined when trying to access any object after apis. How do I retrieve and post to my resource?
